#!/bin/bash
### BEGIN INIT INFO
# Provides:          springboot-alf
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Spring Boot Application - your description here
### END INIT INFO

# Adjust these paths as needed
APP_PATH="/opt/springboot-alf/SpringBoot-ALF-*.jar"
JAVA_CMD="/usr/bin/java"
USER="root"

case "$1" in
  start)
    echo "Starting Spring Boot Application..."
    su - $USER -c "$JAVA_CMD -jar $APP_PATH &"
    ;;
  stop)
    echo "Stopping Spring Boot Application..."
    PID=$(pgrep -f $APP_PATH)
    kill $PID
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0