name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./SpringBoot-ALF

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  build-deb-installer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle Wrapper
      run: ./gradlew bootJar

    - name: Build docker image
      run: docker build -t debian-packager .

    - name: Run docker container
      run: docker run --name packager -v $(pwd):/package/src debian-packager

    - name: Copy debian package from docker container
      run: docker cp packager:/package/springboot-alf_1.0_all.deb ./

    - name: Upload Debian Installer
      uses: actions/upload-artifact@v4
      with:
        name: Debian installer
        path: ./SpringBoot-ALF/*.deb